### ISSUE TITLE
Support for MFA in assuming roles

### ISSUE THREAD

**Issue by fabiomsouto** [awslabs/amazon-ecs-local-container-endpoints#27] opened 2019-10-24 14:32 UTC
Hey,

For our particular setup, which requires the use of MFA, I get

ecs-local-endpoints_1  | time="2019-10-24T14:23:00Z" level=fatal msg="Failed to create Credentials Service: AssumeRoleTokenProviderNotSetError: assume role with MFA enabled, but AssumeRoleTokenProvider session option not set."

Is there an alternative way to do this?

Cheers!

**Comment by PettitWesley** [comment] 2019-11-21 06:57
@fabiomsouto I think the issue is in how to support getting the MFA token. Local Endpoints runs as a container, there's no clear way to prompt the user for a token.

As a work around, could you run AWS CLI sts commands to get temp creds from your MFA enabled role, then set those creds as Env Vars, and launch local container endpoints to use those environment variables. Its not ideal, but you could write a "launch script" for your project which prompts for MFA on the command line, gets creds, sets env vars, and then launches local container endpoints.

**Comment by fabiomsouto** [comment] 2019-11-25 09:25
Sounds good, will give that a go! If it works I'll share the script.

Thanks.

**Comment by efekarakus** [comment] 2020-02-17 21:46
Resolving this issue, please feel free to re-open it if the workaround didn't solve your issue!

**Closed by efekarakus** 2020-02-17 21:46 UTC
